### ISSUE TITLE
Re-release dataset with updated Glottocode mapping

### ISSUE THREAD

**Issue by xrotwang** [digling/servamalagasy#8]
Glottolog's classification of Malagasy is now largely based on Serva's paper (and thus this dataset). So re-checking the Glottocode mappings and recreating/-releasing the dataset based on Glottolog 4.6 would add value.

**Comment by LinguList** [comment]
Ah perfect. Also a nice example, how this feeds back to Glottolog.

**Comment by LinguList** [comment]
I just invited @MuffinLinwist, student assistant working on lexibank and cldf to this repository and will ask him to look into the refined Glottocodes as part of the tasks for next week.

**Comment by LinguList** [comment]
@xrotwang, are the glottocodes fine in the new version, which @MuffinLinwist provided?

**Comment by xrotwang** [comment]
Yes, looks ok.
